### ISSUE TITLE
NPM Dependency

### ISSUE THREAD

**Issue by ghost** [relatenow/relate#11]
Hey Sébastien,

After some contributions on the ran project I decided to follow my own idealistic path to a npm dependency library for next.js. Ran is an awesome project but I feel like going faster to this npm goal, as I would like to use that asap in my future projects. Please feel free to contribute [next.js-library](https://github.com/astenmies/next.js-library), I'm currently at a very eeearly stage (not much to see yet).

Cheers!

**Comment by sedubois** [comment]
Hey I'm glad to see more and more projects to combine an optimal webapp UX and DX. As you saw here, I've put development on pause because my time is taken elsewhere (more news on that soon), so the same applies to your project at the moment unfortunately. I wish you however all the best, and also recommend joining forces with other developers.
