### ISSUE TITLE
[Question] Checking for SSR in WithIntl HOC

### ISSUE THREAD

**Issue by rockchalkwushock** [relatenow/relate#12]
@sedubois 

I'm looking at how you are implementing `react-intl` with `next` and have a question about `serverRendered` in the [WithIntl HOC](https://github.com/relatenow/relate/blob/master/hocs/withIntl.js#L17). Is this being set by `next` somewhere? I have been looking through the source code trying to figure out where this value would be getting set from `true` on the initial render to `false` there after.

It's my understanding that it is `_document` that is loaded from the server-side and that the view from `pages/index.js` would be returned from `<Main />` which is returned from `<Document />`. I'm just not following where this boolean is being set by `next`.

Thanks for your help and explanation! 😃

**Comment by sedubois** [comment]
HI @rockchalkwushock, I set `serverRendered` in the [`withAuth`](https://github.com/relatenow/relate/blob/809b1af19cb94ee2b4307dd431916a6a019b38a8/hocs/withAuth.js#L24) HOC by checking whether `process.browser` exists or not. This is an implicit API dependency between both HOCs, so it's not perfect indeed. This works because both HOCs are composed in [`page`](https://github.com/relatenow/relate/blob/a5cd1af80dfe6d5d10a9a676c2f0a99ff172c483/hocs/page.js#L9).

Hope that helps. Closing issue but feel free to comment.

**Comment by rockchalkwushock** [comment]
@sedubois

I see. I had not looked on that HOC. I spoke with @tim in the #next channel and he said he thought that webpack was setting/providing process.browser & process.isServer at runtime. I have not had a chance to look into this since I’m out of state at the moment. Thanks for the better understanding of how you were setting this!
